# this is a PoC environment extension of basic DNS server environment with the following sample DNS service:
# - each dns service has now it own SML management service based  on the DomiSML project

include:
  - ../docker-compose.yml


services:
  # the top domain SML service for zone 0088.iso6523.participants.participants.ecosystem.org
  ecosystem-top-domain-sml:
    image: domisml:5.0-SNAPSHOT
    container_name: ecosystem-top-domain-sml
    depends_on:
      - ecosystem-top-domain
    environment:
      DNS_ENABLED: true
      DNS_HOSTNAME: ecosystem-top-domain
      DNS_DOMAIN: participants.ecosystem.org
      DNS_ZONE: ecosystem.org
      PARTICIPANT_ID_REGEXP: ^(?!0195:|9914:)[0-9]{4}:.*$$
      IDENTIFIER_DNS_TEMPLATE: >
        MATCH_SCHEME_REGEXP:^(?i)(iso6523-actorid-upis);
        ID_TMPL:$${scheme}\:\:$${identifier};
        ID_SPLIT_REGEXP:^(?i)\\s*(\:\:)?(?<scheme>(iso6523-actorid-upis))\:\:?(?<identifier>.+)?\\s*$$;
        DNS_SUFFIX_TMPL:$${icd}.$${scheme};
        DNS_SUFFIX_SPLIT_REGEXP:^(?i)\\s*(\:\:)?(?<scheme>(iso6523-actorid-upis))\:\:?(?<icd>[0-9]{4})?\:(?<identifier>.+)?\\s*$$;
        DNS_HASH_MODE:IDENTIFIER_IN_HASH
    ports:
      - 10088:8080
    networks:
      test-dns-net:
        ipv4_address: 172.20.0.202

  # the delegated zone 0195.iso6523.participants.ecosystem.org
  invoice-sg-sml:
    image: domisml:5.0-SNAPSHOT
    container_name: invoice-sg-sml
    depends_on:
      - invoice-sg
    environment:
      DNS_ENABLED: true
      DNS_HOSTNAME: invoice-sg
      DNS_DOMAIN: 0195.iso6523-actorid-upis.participants.ecosystem.org
      DNS_ZONE: 0195.iso6523-actorid-upis.participants.ecosystem.org
      PARTICIPANT_ID_REGEXP: ^0195:.*$$
      IDENTIFIER_DNS_TEMPLATE: >
        MATCH_SCHEME_REGEXP:^(?i)(iso6523-actorid-upis);
        ID_TMPL:$${scheme}\:\:$${identifier};
        ID_SPLIT_REGEXP:^(?i)\\s*(\:\:)?(?<scheme>(iso6523-actorid-upis))\:\:?(?<identifier>.+)?\\s*$$;
        DNS_SUFFIX_TMPL:$${icd}.$${scheme};
        DNS_SUFFIX_SPLIT_REGEXP:^(?i)\\s*(\:\:)?(?<scheme>(iso6523-actorid-upis))\:\:?(?<icd>[0-9]{4})?\:(?<identifier>.+)?\\s*$$;
        DNS_HASH_MODE:IDENTIFIER_IN_HASH
    ports:
      - 10195:8080
    networks:
      test-dns-net:
        ipv4_address: 172.20.0.203

  # the redirected zone 0195.iso6523.participants.ecosystem.org
  vat-num-at-sml:
    image: domisml:5.0-SNAPSHOT
    container_name: vat-num-at-sml
    depends_on:
      - vat-num-at
    environment:
      DNS_ENABLED: true
      DNS_HOSTNAME: vat-num-at
      DNS_DOMAIN: 9914.iso6523-actorid-upis.g2b.at
      DNS_ZONE: 9914.iso6523-actorid-upis.g2b.at
      PARTICIPANT_ID_REGEXP: ^9914:.*$$
      IDENTIFIER_DNS_TEMPLATE: >
        MATCH_SCHEME_REGEXP:^(?i)(iso6523-actorid-upis);
        ID_TMPL:$${scheme}\:\:$${identifier};
        ID_SPLIT_REGEXP:^(?i)\\s*(\:\:)?(?<scheme>(iso6523-actorid-upis))\:\:?(?<identifier>.+)?\\s*$$;
        DNS_SUFFIX_TMPL:$${icd}.$${scheme};
        DNS_SUFFIX_SPLIT_REGEXP:^(?i)\\s*(\:\:)?(?<scheme>(iso6523-actorid-upis))\:\:?(?<icd>[0-9]{4})?\:(?<identifier>.+)?\\s*$$;
        DNS_HASH_MODE:IDENTIFIER_IN_HASH
    ports:
      - 19914:8080
    networks:
      test-dns-net:
        ipv4_address: 172.20.0.204
